ecofunds/project/urls.py
from django.conf.urls.defaults import *
from ecofunds.project.views import *

urlpatterns = patterns('django.views.generic.list_detail',
    (r'^suggest', ProjectSuggestListView.as_view(data_type="html")),
    (r'^countries', CountriesSuggestListView.as_view(data_type="html")),
    (r'^regions', RegionsSuggestListView.as_view(data_type="html")),
    (r'^list', ProjectListView.as_view(template_name='project/list.html')),
    (r'^excel', ProjectFilteredListExcel.as_view()),
    (r'^resumes', ProjectListView.as_view(template_name='project/resumes.html')),
    (r'^mapsource', ProjectMapSourceView.as_view()),
    (r'^chartsource', ProjectChartSourceView.as_view()),
    (r'^geoip', GeoIpView.as_view()),
    (r'^remove',remove_project),
)

ecofunds/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

from ecofunds.views import *

from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^opportunity/', include('ecofunds.opportunity.urls')),
    url(r'^ajax/lookups',include(ajax_select_urls)),
    url(r'^ajax/project/', include('ecofunds.project.urls')),
    url(r'^ajax/organization/', include('ecofunds.organization.urls')),
    url(r'^ajax/investment/', include('ecofunds.investment.urls')),
    #url(r'^ajax/suggest', GlobalSuggestListView.as_view()),
    url(r'^ajax/suggest', SearchSuggestListView.as_view()),
    url(r'^ajax/upload', uploadify_upload),
    url(r'^attachment/download/(?P<id>[\d]+)/$', FileDownload.as_view()),
    url(r'^maps/', include('ecofunds.maps.urls')),
    url(r'^user/',include('ecofunds.user.urls')),
    url(r'^new/$',AttachmentCreateView.as_view(),{},'upload-new'),
    url(r'^delete/(?P<pk>\d+)$',AttachmentDeleteView.as_view(),{},'upload-delete'),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        (r'^' + settings.MEDIA_URL.lstrip('/'), include('appmedia.urls')),
    ) + urlpatterns

ecofunds/project/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin, Page
from django.core import validators

class SearchProjectPlugin(CMSPlugin):
    page_result = models.ForeignKey(
                    Page,
                    verbose_name=_("Page result"),
                    blank=True,
                    null=True,
                    help_text=_("Link to result page.")
                  )

class DetailProjectPlugin(CMSPlugin):
    pass

class ProjectsPlugin(CMSPlugin):
    page_detail = models.ForeignKey(
                    Page,
                    verbose_name=_("Page detail"),
                    blank=True,
                    null=True,
                    help_text=_("Link to detail page.")
                  )
    card_limit = models.PositiveIntegerField(
        _('Number of news items to show'), 
        help_text=_('Limits the number of items that will be displayed')
    )

    table_limit = models.PositiveIntegerField(
        _('Number of news items to show'), 
        help_text=_('Limits the number of items that will be displayed')
    )

    def __unicode__(self):
        return ""

class ProjectFormPlugin(CMSPlugin):
    pass

ecofunds/project/forms.py
from django import forms
from django.core.cache import cache
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from ecofunds.models import Activity,Project, Currency
from ecofunds.forms import AdvancedSearchForm
from ajax_select import make_ajax_field

import datetime

from django.utils.encoding import force_unicode
from django.utils.safestring import mark_safe

class MyRadioFieldRenderer(forms.widgets.RadioFieldRenderer):

    def render(self):
        """Outputs a <ul> for this set of radio fields."""
        return mark_safe(u'<ul class="radio-buttons">\n%s\n</ul>' % 
                u'\n'.join([u'<li>%s</li>'
                % force_unicode(w) for w in self]))

#PROJECT_TYPES_CHOICES = (
#    ('1','Choose an activity type'),
#    ('2','Aquatic conservation'),
#    ('3','Access and benefit sharing'),
#    ('4','Biocommerce'),
#    ('5','Capacity building&nbsp; Institutional strengthening'),
#    ('6','Climate change (not REDD+)'),
#    ('7','Law/Regulation'),
#    ('8','Financial mechanisms'),
#    ('9','Funding / Supporting Projects'),
#    ('10','Education / Awareness'),
#    ('11','Indigenous people and local communities'),
#    ('12','Landscape conservation'),
#    ('13','Mitigation/Compensation of impacts'),
#    ('14','Networks'),
#    ('15','Payment for environmental services'),
#    ('16','Protected areas'),
#    ('17','REDD/REDD+'),
#    ('18','Research / Monitoring'),
#    ('19','Species management'),
#    ('20','Sustainable development'),
#    ('21','Sustainable production'),
#    ('22','Voluntary standards'),
#    ('23','Waste treatment')
#)

ACTIVITY_CHOICES = (('', 'Choose an activity type'),) + tuple(Activity.objects.all().values_list('activity_id', 'name'))

class ProjectAdvancedSearchForm(AdvancedSearchForm):

    s_project_name = forms.CharField(label=_('Project name'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a project')}))
    s_all_project_name = forms.BooleanField(label=_('All projects'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))    

    s_project_activity_type = forms.IntegerField(label=_('Project activity type'), widget=forms.Select(choices=ACTIVITY_CHOICES, attrs={'class':''}))

    s_all_project_activity_type = forms.BooleanField(label=_('All activities types'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_type_organization = forms.CharField(label=_('Organization type'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter an organization type')}))
    s_all_type_organizations = forms.BooleanField(label=_('All organization types'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_organization = forms.CharField(label=_('Organization'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of an organization')}))
    s_all_organizations = forms.BooleanField(label=_('All organizations'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_country = forms.CharField(label=_('Country'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a country')}))
    s_state = forms.CharField(label=_('State'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a state')}))

    s_investments_from = forms.CharField(label=_('Show investments from:'), widget=forms.TextInput(attrs={'class':'numero'}))
    s_investments_to = forms.CharField(label=_('to'), widget=forms.TextInput(attrs={'class':'numero'}))


    s_date_from = forms.DateTimeField(label=_('Execution period:'), widget=forms.TextInput(attrs={'class':'data'}))
    s_date_to = forms.CharField(label=_('to'), widget=forms.TextInput(attrs={'class':'data'}))


    def _force_data(self):
        if not hasattr(self, 'cleaned_data'):
            self.is_valid()
        if not hasattr(self, 'cleaned_data'):
            self.cleaned_data = {}

    def get_value(self, key, persist=False):
        
        value = None
        #if self.data.has_key(key):
        #    
        #    self._force_data()
        #    if self.cleaned_data.has_key(key):
        #        value = self.cleaned_data[key]

        #    if value:
        #        cache.set(key, value)
        #    else :
        #        value = self.data.get(key)

        #        if not value:
        #            value = cache.get(key)
        #            self.cleaned_data[key] = value
        #        else:
        #            cache.set(key, value)
        #else:
        #    if persist:
        #        value = cache.get(key)
        #        self._force_data()
        #        self.cleaned_data[key] = value
        #    else:
        #        cache.delete(key)

        if hasattr(self, 'cleaned_data') and self.cleaned_data.has_key(key):
            value = self.cleaned_data[key]

        if not value:
            value = self.data.get(key, '')

        if not value:
            value = self.initial.get(key, '')

        return value

class ProjectForm(ModelForm):
    title = forms.CharField(label=_('Project name'), required=True, widget=forms.TextInput(attrs={'placeholder': _('Enter the name of a project')}))
    acronym = forms.CharField(label=_('Acronym'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Enter the abbreviation of a project')}))
    description = forms.CharField(label=_('Project description'), required=True, widget=forms.Textarea(attrs={'placeholder': _('Enter the description of a project')}))
    
    cat_choices = [('True',_('Project')),('False',_('Program'))]
    category = forms.ChoiceField(choices=cat_choices,widget=forms.RadioSelect(renderer=MyRadioFieldRenderer),initial='True',required=True)

    includes_choices = [('True',_('Yes')),('False',_('No'))]
    include = forms.ChoiceField(choices=includes_choices, widget=forms.RadioSelect(renderer=MyRadioFieldRenderer),
            label=_("Is the project or program included in a program?"),initial='False',required=False)
    
    grant_from = forms.DateField(label=_("Start date"), required=True, widget=forms.DateInput(attrs={'class':'data'}))
    grant_to = forms.DateField(label=_("Expected completion"), required=True, widget=forms.DateInput(attrs={'class':'data'}))

    currency = forms.ModelChoiceField(queryset=Currency.objects.all(),label=_('Estimated budget'), required=True, widget=forms.Select(attrs={'class':'select-curto moeda'}))
    budget = forms.FloatField(widget=forms.TextInput(attrs={'class':'numero'}), required=True)
    
    email = forms.EmailField(label=_('Email'), required=True, widget=forms.TextInput(attrs={'placeholder': _('Enter the email')}))

    phone_country_prefix_01 = forms.CharField(label=_('Phone number 01'), required=True, widget=forms.TextInput(attrs={'class':'prefixo',  'maxlength':'2'}))
    phone_local_prefix_01 = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'prefixo',  'maxlength':'2'}))
    phone_number_01 = forms.CharField(label=_('Phone number 01'), required=True, widget=forms.TextInput(attrs={'class':'telefone'}))
    
    phone_country_prefix_02 = forms.CharField(label=_('Phone number 02'), required=False, widget=forms.TextInput(attrs={'class':'prefixo',  'maxlength':'2'}))
    phone_local_prefix_02 = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'prefixo',  'maxlength':'2'}))
    phone_number_02 = forms.CharField(label=_('Phone number 02'), required=False, widget=forms.TextInput(attrs={'class':'telefone'}))
    
    fax_country_prefix = forms.CharField(label=_('FAX'), required=False, widget=forms.TextInput(attrs={'class':'prefixo',  'maxlength':'2'}))
    fax_local_prefix = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'prefixo',  'maxlength':'2'}))
    fax = forms.CharField(label=_('FAX'), required=False, widget=forms.TextInput(attrs={'class':'telefone'}))

    website = forms.CharField(label=_('Website'), required=False, widget=forms.TextInput(attrs={'placeholder': _('Enter the website')}))

    #activities = forms.ModelChoiceField(queryset=Activity.objects.all(),required=True)
    activity_description = forms.CharField(label=_('Activity description'), required=False, widget=forms.Textarea(attrs={'placeholder': _('Enter the description of activity')}))

    class Meta:
        model = Project
        exclude = ('entity_id',)
        fields = ('title','description','acronym','image','category','include','organization',
                'main_organization','grant_from','grant_to','currency','budget','email','phone_local_prefix_01','phone_country_prefix_01','phone_number_01',
                'phone_country_prefix_02','phone_country_prefix_02',
                'phone_number_02','fax_country_prefix','fax_local_prefix','fax','website','locations','activities','activity_description')

    main_organization = make_ajax_field(Project,'main_organization','organization', help_text=_('Enter text to search'), label=_('Main executor organization'), required=True)
    organization = make_ajax_field(Project,'organization','organization',help_text=_('Enter text to search'),label=_('Add other executor organizations'), required=False)
    locations = make_ajax_field(Project,'locations','location',help_text=_('Enter text to search'),label=_('Add countries, states and cities where the project is'), required=True)
    activities = make_ajax_field(Project,'activities','activity',help_text=_('Enter text to search'),label=_('Add activity types'), required=True)
    child_projects = make_ajax_field(Project,'sub_projects','project',help_text=('Enter text to search'),label=_('Add a project'),required=False)

ecofunds/templates/project/advanced-search.html
{% load tags i18n %}

<!-- Filtros de Busca por Projetos -->
<section class="filtros projetos aberto">
    <header class="cabecalho">
        <h4>{% trans "Search projects by" %}</h4>
        <p><span class="seta cima cinza"></span>{% trans "Combine filters to improve your search" %}</p>
        <a class="botao primario ocultar-exibir-filtro" href="#" title=""><span class="ico pequeno seta"></span></a>
    </header>
    
    <form class="form-filtros projetos" action="#" method="post">
        {{ search_project_form.page }}
        {{ search_project_form.limit }}
        {{ search_project_form.list_type }}
        {{ search_project_form.order_by }}

        <div class="borda primeiro">
            <fieldset>
                <legend>{% trans "Name" %} <span class="total">({{ count_projects }})</span></legend>

                {{ search_project_form.s_project_name }}

                <label for="id_s_all_project_name" class="check"> 
                    {{ search_project_form.s_all_project_name }}
                    {{ search_project_form.s_all_project_name.label }}
                </label>                    

            </fieldset>
        </div>

        <div class="borda">
            <fieldset>
                <legend>{% trans "Activity Type" %} <span class="total">({{ count_project_activity_types }})</span></legend>

                {{ search_project_form.s_project_activity_type }}

                <label for="id_s_all_project_activity_type" class="check"> 
                    {{ search_project_form.s_all_project_activity_type }}
                    {{ search_project_form.s_all_project_activity_type.label }}
                </label>                    

            </fieldset>
        </div>

        <div class="borda">
            <fieldset>
                <legend>{% trans "Region" %} <span class="total">({{ count_project_regions }})</span></legend>
                
                <label for="id_s_country">{{ search_project_form.s_country.label }}</label>
                {{ search_project_form.s_country }}

                <label for="id_s_state">{{ search_project_form.s_state.label }}</label>
                {{ search_project_form.s_state }}

            </fieldset>
        </div>

        <div class="borda">
            <fieldset>
                <legend>{% trans "Organization" %} <span class="total">({{ count_organizations }})</span></legend>
                
                {{ search_project_form.s_organization }}

                <label for="id_s_all_organizations" class="check"> 
                    {{ search_project_form.s_all_organizations }}
                    {{ search_project_form.s_all_organizations.label }}
                </label>

            </fieldset>
        </div>
        
        <div class="borda">
            <fieldset>
                <legend>{% trans "Annual budget" %} <!--<span class="total">({{ count_investments }})</span>--></legend>
                
                <label for="id_s_investments_from">{{ search_project_form.s_investments_from.label }}</label>
                {{ search_project_form.s_investments_from }}

                <label class="emlinha" for="id_s_investments_to">{{ search_project_form.s_investments_to.label }}</label>
                {{ search_project_form.s_investments_to }}
            </fieldset>
        </div>

        <div class="borda ultimo">
            <fieldset>
                <legend>{% trans "Execution" %}</legend>
                
                <label for="id_s_date_from">{{ search_project_form.s_date_from.label }}</label>
                {{ search_project_form.s_date_from }}

                <label class="emlinha" for="id_s_date_to">{{ search_project_form.s_date_to.label }}</label>
                {{ search_project_form.s_date_to }}
            </fieldset>
        </div>
    </form>
    
    {% block extra_script %}
    <script type="text/javascript">
        jQuery(document).ready(function(){
            //Cria o estilo dos elementos combo.
            createCombo();

            //Chama o plugin de datepicker do jqueryUI.
            jQuery('.data').datepicker({dateFormat:'{{date_format}}'});

            //Formatação do campo de valor. Classe específica = numero
            jQuery('.numero').setMask('{{number_format}}');
        });
    </script>
    {% endblock %}    
</section>
<!-- Fim de Filtros de Busca por Projetos -->

ecofunds/templates/project/list.html
{% load sekizai_tags tags i18n static cms_tags %}
{%block head%}
    {% addtoblock "css" %}
        <link type="text/css" rel="stylesheet" href="{% get_static_prefix %}css/ui-custom-theme/jquery-ui-1.9.2.custom.min.css" />
    {% endaddtoblock %}
    
    {% addtoblock "js" %}
        <!-- Funções gerais de cadastro -->
        <script type="text/javascript" src="{% get_static_prefix %}scripts/global/list.js"></script>
                        
        <!-- Funções específicas dessa página -->
        <script type="text/javascript" src="{% get_static_prefix %}scripts/project/list.js"></script>
    {% endaddtoblock %}
{% endblock %}

<!-- area-site -->
<div class="area-site">
    <div class="container">
        <h2 class="ico ico-texto projeto-maior-branco">{% trans "Projects" %}</h2>    
    </div>
</div>
<!-- fim area-site -->

<div class="container">
    <!-- Link auxiliar -->
    <div class="link-auxiliar">    
        <a class="link-destaque" href="javascript:;" title="{% trans "Show all projects" %}">{% trans "Show all projects" %}</a>
    </div>
    <!-- fim de Link auxiliar -->
    
    <!-- conteudo principal -->
    <div class="conteudo filtros-listas-tabelas">
        {% if labels %}
            <!-- Filtros Aplicados -->
            <div class="filtros-aplicados">
                <p>{% trans "Filters: " %}</p>
                <ul class="lista">
                    {% for k, v in labels.items %}
                    <li class="item etiqueta" title="{% field_label search_project_form k %}" data-field="{{ k }}">{{ v }} <span class="fechar-filtro"></span></li>
                    {% endfor %} 
                </ul>
            </div>
            <!-- fim de Filtros Aplicados -->
        {% endif %}

        {% if list|count > 0 %}
            <!-- visualizacao -->
            <div class="visualizacao">
                <p class="texto-lista">{% trans "View: " %}</p>
                <ul class="visualizacao-container">
                    <li class="item {% if search_project_form.list_type.value == None or search_project_form.list_type.value == '1'%}ativo{% else %}inativo{% endif %}">
                        <a href="#listagem" class="link ico ico-texto grid-icone {% if search_project_form.list_type.value == None or search_project_form.list_type.value == '1' %}ativo{% else %}inativo{% endif %}">{% trans "Grid" %}
                        </a>
                    </li>
                    
                    <li class="item {% if search_project_form.list_type.value == '2' %}ativo{% else %}inativo{% endif %}">
                        <a href="#tabela" class="link ico ico-texto lista-icone {% if search_project_form.list_type.value == '2' %}ativo{% else %}inativo{% endif %}">{% trans "List" %}
                        </a>
                    </li> <!-- Para cada um desses, existe um icone inativo -->
                </ul>
            </div>
            <!-- fim de visualizacao -->
            
            <!-- Ordenacao -->  
            <div class="ordenacao">
                <p>{% trans "Order by: " %}</p>
                <ul class="lista">
                    <li class="item atual"><a href="#-created_at">{% trans "Latest projects" %}</a></li>
                    <li class="item"><a href="#title">{% trans "A-Z" %}</a></li>
                    <li class="item"><a href="#-budget">{% trans "Highest budget" %}</a></li>
                    <li class="item"><a href="#budget">{% trans "Lowest budget" %}</a></li>
                    <li class="item"><a href="#-grant_to">{% trans "Completion date" %}</a></li> 
                </ul>
            </div>
            <!-- fim de Ordenacao -->
        {%endif%}
       
        <!-- modos de visualizacao -->
        <div class="modos-visualizacao">
            <!-- listagem de projetos -->
            <section id="listagem" class="listagem projetos">                
                {% if list|count > 0 %}
                    <!-- Paginação -->
                    {% pagination list %}

                    {% for project,perm in itempermlist %}
                        <!-- cartao-projeto -->
                        <div class="cartao projeto {% if forloop.counter|mod:3 == 1 %}primeiro{% endif %} {%if perm%}pode-editar{%endif%}" data-index="{{ project.pk }}">
                            <h3 class="titulo" title="{{ project.title }}">{{ project.title }}</h3>

                            <p class="subtitulo">
                            {% if project.get_firstlocation.location.country.name %}
                                <a href="#" onclick="$('#id_s_country').val('{{ project.get_firstlocation.location.country.name }}').keyup();return false;" class="country">{{ project.get_firstlocation.location.country.name }}</a> - <a href="#" onclick="$('#id_s_state').val('{{ project.get_firstlocation.location.name }}').keyup();return false;" class="state">{{ project.get_firstlocation.location.name }}</a>
                            {%else%}<span style="visibility:hidden">-</span>
                            {%endif%}
                            </p>
                        
                            <img class="thumb" src="{% if project.image %}{{ project.image.url }}{% else %}{% get_static_prefix %}images/projeto-sem-foto.jpg{% endif %}" alt="{% trans "Project Image" %}" />
                            <p class="invest-recebido">
                                {% trans "Current Investments:" %}
                                <span class="valor">{%if project.get_current_investment and project.get_current_investment.amount_usd %}{% currency project.get_current_investment.amount_usd %}{% else %}{% currency 0 %}{% endif %}</span>
                            </p>
                            
                            <p><strong>{% trans "Annual budget: " %}</strong>{% currency project.budget %}</p>
                            <p><strong>{% trans "Completion date: " %}</strong>{{ project.grant_to|date:"d/M/Y" }}</p> <!-- Acrescentei essa linha para formatar a data -->
                            
                            <p class="resumo" title="{% autoescape off %}{{ project.resume }}{% endautoescape %}">
                                {% autoescape off %}{{ project.resume }}{% endautoescape %}
                            </p>
                            <a class="veja-mais" href="{% page_url page_detail %}?id={{ project.entity_id }}" title="{% trans "More information" %}">{% trans "More information" %}</a>
                            {%if perm%}
                                <div class="controles-edicao lista projeto">
                                    <a class="ico pequeno editar" href="{% page_url "project-form" %}?id={{ project.entity_id }}" title="{% trans "Edit project" %}: {{ project.title }}">Edit</a>
                                    <a class="ico pequeno excluir" href="javascript:;" title="{% trans "Delete project" %}: {{ project.title }}">Delete</a>
                                </div>
                                
                                <div class="camada-exclusao projeto">
                                    <div class="confirmacao">
                                        <p>{% trans "The project" %} <em>{{ project.title }}</em> {% trans "will be deleted from Ecofunds and can only be recovered by an Ecofunds accountable  person or an organization administrator." %}</p>
                                        
                                        <p>{% trans "Do you really want to delete this project from Ecofunds?" %}</p>
                                        
                                        <a class="botao primario cancelar" href="javascript:;" title="{% trans "No, keep project in Ecofunds" %}">{% trans "No, keep project in Ecofunds" %}</a>
                                        
                                        <a class="confirmar" href="javascript:;" title="{% trans "Yes, delete project" %}">{% trans "Yes, delete project" %}</a>
                                    </div>
                                    
                                    <div class="excluido">
                                        <a class="botao primario ativar" href="javascript:;" title="{% trans "Enable project" %}">{% trans "Enable project" %}</a>
                                    </div>
                                </div>
                            {%endif%}      
                        </div>
{% if project.is_completed %}
    <div class="faixa-conclusao">
         {% trans "Project completed"%}
    </div>
{% endif%}
                        <!-- fim de cartao-projeto -->
                    {% endfor %}

                    <!-- Paginação -->
                    {% pagination list %}                    
                {% else %}
                    {% include "no-results.html" %}
                {% endif %}
            </section>
            <!-- fim de listagem de projetos -->
            
            
            <!-- tabela projetos -->
            <section id="tabelas" class="tabelas projetos">
                {%if list|count%}
                    <div class="cabecalho-tabela">
                        <h2 class="titulo-tabela">{% trans "Projects" %}</h2>
                        <span class="gerar-relatorio ico ico-texto relatorio"><a href="/ajax/project/excel">{% trans "Generate Report" %}</a></span>
                    </div>

                    <!-- tabela -->
                    <table class="tabela vertical" caption="Supported projects / Executed projects" summary="">
                        <thead>
                            <tr>
                                <th class="titulo-registro" scope="col">{% trans "Name" %}</th>
                                <th class="titulo-registro" scope="col">{% trans "Completion date" %}</th>
                                <th class="titulo-registro" scope="col">{% trans "Received total (U$)" %}</th>
                                <th class="titulo-registro" scope="col">{% trans "Region" %}</th>
                                <th class="titulo-registro" colspan="2" scope="col"></th>
                            </tr>
                        </thead>

                        <tfoot>
                            <!-- Paginação -->
                            <tr>
                                <td class="rodape-tabela" colspan="6">
                                    <div class="paginacao-resultados">
                                        {% pagination list True %}
                                    </div>
                                </td>
                            </tr>
                            <!-- Fim de Paginação -->
                        </tfoot>

                        <tbody>
                            {% for project in list %}
                            <tr>
                                <td class="conteudo-registro texto-linha medio"><a href="{% page_url page_detail %}?id={{ project.entity_id }}" title="{{ project.title }}">{{ project.title }}</a></td>
                                <td class="conteudo-registro data">{{ project.grant_to|date:"d/M/Y" }}</td>
                                <td class="conteudo-registro valor">{%if project.get_current_investment and project.get_current_investment.amount_usd %}{% currency project.get_current_investment.amount_usd %}{% else %}{% currency 0 %}{% endif %}</td>
                                <td class="conteudo-registro regiao">{{ project.get_firstlocation.name }} - {{ project.get_firstlocation.iso_cc }}</td>
                                <td class="conteudo-registro link"><a href="{% page_url page_detail %}?id={{ project.entity_id }}" title="">{% trans "Project record" %}</a></td>
                                <td class="conteudo-registro link"><a href="{%page_url "map"%}?s_project_name={{project.title}}" title="">{% trans "Location map" %}</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>                
                    <!-- fim de tabela  -->
                {%else%}
                    {%include "no-results.html"%}
                {%endif%}
            </section>
            <!-- fim de tabela projetos -->

        </div>
        <!-- fim de modos de visualizacao -->
    </div>
    <!-- fim de conteudo -->

    <!-- barra lateral -->
    <div class="barra-lateral">
        {% include "project/advanced-search.html" %}

        {% include "./map-link.html" %}
    </div>
    <!-- fim de barra lateral -->
</div>

ecofunds/templates/project/search.html
{% load tags static i18n %}
<!-- busca-projetos -->
<section class="filtros home">
    <header class="cabecalho">
        <h4>{% trans "Search projects by" %}</h4>
    </header>

    <form class="form-filtros home" action="{% page_url page_result %}" method="POST">
        {% csrf_token %}
        <label for="id_s_project_name">{% trans "Name" %}</label>                  
        {{ search_project_form.s_project_name }}
        
        <label for="id_s_organization">{% trans "Organization" %}</label>                   
        {{ search_project_form.s_organization }}

        <label for="id_s_country">{% trans "Country" %}</label>                  
        {{ search_project_form.s_country }}
        
        <input type="submit" value="{% trans "Search projects" %}" />
    </form>
    
    {% block extra_script %}
    <script type="text/javascript">
        jQuery(document).ready(function(){
            //Cria o estilo dos elementos combo.
            createCombo();
        });
    </script>
    {% endblock %}    
</section>
<!-- fim de busca-projetos -->