ecofunds/investment/urls.py
from django.conf.urls.defaults import *
from ecofunds.investment.views import *

urlpatterns = patterns('django.views.generic.list_detail',
    (r'^flowsource/(?P<id>\d+)', InvestmentFlowSource.as_view()),
    (r'^mapsource', InvestmentMapSourceView.as_view()),
    (r'^remove',remove_investment),
)

ecofunds/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

from ecofunds.views import *

from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^opportunity/', include('ecofunds.opportunity.urls')),
    url(r'^ajax/lookups',include(ajax_select_urls)),
    url(r'^ajax/project/', include('ecofunds.project.urls')),
    url(r'^ajax/organization/', include('ecofunds.organization.urls')),
    url(r'^ajax/investment/', include('ecofunds.investment.urls')),
    #url(r'^ajax/suggest', GlobalSuggestListView.as_view()),
    url(r'^ajax/suggest', SearchSuggestListView.as_view()),
    url(r'^ajax/upload', uploadify_upload),
    url(r'^attachment/download/(?P<id>[\d]+)/$', FileDownload.as_view()),
    url(r'^maps/', include('ecofunds.maps.urls')),
    url(r'^user/',include('ecofunds.user.urls')),
    url(r'^new/$',AttachmentCreateView.as_view(),{},'upload-new'),
    url(r'^delete/(?P<pk>\d+)$',AttachmentDeleteView.as_view(),{},'upload-delete'),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        (r'^' + settings.MEDIA_URL.lstrip('/'), include('appmedia.urls')),
    ) + urlpatterns

ecofunds/investment/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin, Page
from django.core import validators


class InvestmentsPlugin(CMSPlugin):

    page_detail = models.ForeignKey(
                    Page,
                    verbose_name=_("Page detail"),
                    blank=True,
                    null=True,
                    help_text=_("Link to detail page.")
                  )
    limit = models.PositiveIntegerField(
                _('Number of news items to show'), 
                help_text=_('Limits the number of items that will be displayed')
            )
    def __unicode__(self):
        return ""

class InvestmentFormPlugin(CMSPlugin):
    pass

ecofunds/investment/forms.py
from django import forms
from django.core.cache import cache
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from ecofunds.models import *
from ecofunds.forms import AdvancedSearchForm
from ajax_select import make_ajax_field

from django.utils.encoding import force_unicode
from django.utils.safestring import mark_safe

class MyRadioFieldRenderer(forms.widgets.RadioFieldRenderer):

    def render(self):
        """Outputs a <ul> for this set of radio fields."""
        return mark_safe(u'<ul class="radio-buttons">\n%s\n</ul>' % 
                u'\n'.join([u'<li>%s</li>'
                % force_unicode(w) for w in self]))

#INVESTMENTTYPE_CHOICES = (
#    ('', 'Choose an investment type'),
#    ('1', 'Donation'),
#    ('1', 'In Kind'),
#    ('1', 'Legal obligations'),
#    ('1', 'Loan'),
#    ('1', 'Matching'),
#    ('1', 'Microcredit'),
#    ('1', 'Voluntary compensations / Mitigations')
#)

#ORGANIZATIONTYPE_CHOICES = (
#    ('', 'Choose an organization type'),
#    ('2', 'Non-profit organization'),
#    ('3', 'Private company'),
#    ('4', 'Government agency'),
#    ('5', 'Bilateral/Multilateral agency'),
#    ('6', 'Academic/Research institution'),
#    ('7', 'Network'),
#    ('8', 'Other')
#)

INVESTMENTTYPE_CHOICES = (('', 'Choose an investment type'),) + tuple(InvestmentType.objects.all().values_list('id', 'name'))
ORGANIZATIONTYPE_CHOICES = (('', 'Choose an organization type'),) + tuple(OrganizationType.objects.all().values_list('id', 'name'))

class InvestmentAdvancedSearchForm(AdvancedSearchForm):
    
    s_investment_type = forms.IntegerField(label=_('Investment type'), widget=forms.Select(choices=INVESTMENTTYPE_CHOICES, attrs={'class':''}))

    s_all_type_investments = forms.BooleanField(label=_('All organization types'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_investment_date_from = forms.CharField(label=_('Show investments from:'), widget=forms.TextInput(attrs={'class':'data'}))
    s_investment_date_to = forms.CharField(label=_('To'), widget=forms.TextInput(attrs={'class':'data'}))
    s_all_investments_date = forms.BooleanField(label=_('All investments received'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_investment_from = forms.CharField(label=_('Show investments from:'), widget=forms.TextInput(attrs={'class':'numero'}))
    s_investment_to = forms.CharField(label=_('To'), widget=forms.TextInput(attrs={'class':'numero'}))
    s_all_investments_value = forms.BooleanField(label=_('All investments value'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_organization_type = forms.IntegerField(label=_('Organization type'), widget=forms.Select(choices=ORGANIZATIONTYPE_CHOICES, attrs={'class':''}))
    
    s_all_type_organizations = forms.BooleanField(label=_('All organization types'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_organization_id = forms.IntegerField(widget=forms.HiddenInput())
    s_organization = forms.CharField(label=_('Organization'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of an organization')}))
    s_all_organizations = forms.BooleanField(label=_('All organizations'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))


    s_project_name = forms.CharField(label=_('Project name'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a project')}))
    s_all_project_name = forms.BooleanField(label=_('All projects'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_country = forms.CharField(label=_('Country'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a country')}))
    s_state = forms.CharField(label=_('State'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a state')}))

    def _force_data(self):
        if not hasattr(self, 'cleaned_data'):
            self.is_valid()
        if not hasattr(self, 'cleaned_data'):
            self.cleaned_data = {}

    def get_value(self, key, persist=False):
        
        value = None
        if hasattr(self, 'cleaned_data') and self.cleaned_data.has_key(key):
            value = self.cleaned_data[key]

        if not value:
            value = self.data.get(key, '')

        if not value:
            value = self.initial.get(key, '')

        return value

class InvestmentForm(ModelForm):
    y_n_choices = [('True',_('Yes')),('False',_('No'))]
    investor_project = forms.ChoiceField(choices=y_n_choices,widget=forms.RadioSelect(renderer=MyRadioFieldRenderer),
            label=_("Is the investment an action of an investor project?"),initial='False',required=False)

    r_project = forms.ChoiceField(choices=y_n_choices,widget=forms.RadioSelect(renderer=MyRadioFieldRenderer),
            label = _("Is the investment direct to a recepient project?"),initial='False',required=False)

    type = forms.ModelChoiceField(queryset=InvestmentType.objects.all(),label=_('Investment type'), widget=forms.Select(attrs={'class':'select-curto'}),required=True)
    date = forms.DateField(label=_('Investment date'), required=True, widget=forms.TextInput(attrs={'class':'data'}))
    estimated_completion = forms.DateField(label=_('Estimated completion date'), required=True, widget=forms.TextInput(attrs={'class':'data'}))

    currency = forms.ModelChoiceField(queryset=Currency.objects.all(),label=_('Investment total value'), required=True, widget=forms.Select(attrs={'class':'select-curto moeda'}))
    amount = forms.FloatField(widget=forms.TextInput(attrs={'class':'numero'}),required=True)
    
    third_party = forms.ChoiceField(choices=y_n_choices,widget=forms.RadioSelect(),label=_('Did the main investor receive this amount from third-party institutions?'),required=False)

    class Meta:
        model = Investment
        fields = ('funding_organization','investor_project','recipient_organization',
                'recipient_entity','funding_entity','r_project','type','date',
                'estimated_completion','currency','amount')

    funding_organization = make_ajax_field(Investment,'funding_organization','organization',help_text=_('Enter text to search'),label=_('Investor organization'), required=True)
    
    recipient_organization = make_ajax_field(Investment,'recipient_organization','organization',help_text=_('Enter text to search'),label=_('Recepient organization'), required=True)
    recipient_entity = make_ajax_field(Investment,'recipient_entity','project',help_text=_('Enter text to search'),label=_('Recipient Project'),
            required = False)
    funding_entity = make_ajax_field(Investment,'funding_entity','project',help_text=_('Enter text to search'),label=_('Investor Project'),
            required = False)

    investment_flow = make_ajax_field(Investment,'investment_flow','investment',help_text=_('Did the main investor received this amount from third-party institutions?'),required=False)

ecofunds/templates/investment/advanced-search.html
{% load tags i18n %}
<!-- Filtros de Busca por Investimentos -->
<section class="filtros investimentos aberto">
    <header class="cabecalho">
        <h4>{% trans "Search investiments by" %}</h4>
        <p><span class="seta cima cinza"></span>{% trans "Combine filters to improve your search" %}</p>
        <a class="botao primario ocultar-exibir-filtro" href="#" title=""><span class="ico pequeno seta"></span></a>           
    </header>

    <form class="form-filtros investimentos" action="#" method="post">
        {{ search_investment_form.page }}
        {{ search_investment_form.limit }}
        {{ search_investment_form.list_type }}
        {{ search_investment_form.order_by }}
        
        <div class="borda primeiro">
            <fieldset>
                <legend>{% trans "Type" %} <span class="total">({{count_investment_types}})</span></legend>
                
                {{ search_investment_form.s_investment_type }}

                <label for="id_s_all_type_investments" class="check"> 
                    {{ search_investment_form.s_all_type_investments }}
                    {{ search_investment_form.s_all_type_investments.label }}
                </label>
            </fieldset>
        </div>

        <div class="borda">
            <fieldset>
                <legend>{% trans "Date" %} <span class="total">({{count_investments}})</span></legend>
    
                <label for="id_s_investment_date_from">{{ search_investment_form.s_investment_date_from.label }}</label>
                {{ search_investment_form.s_investment_date_from }}

                <label class="emlinha" for="id_s_investment_date_to">{{ search_investment_form.s_investment_date_to.label }}</label>
                {{ search_investment_form.s_investment_date_to }}

                <label for="id_s_all_investments_date" class="check"> 
                    {{ search_investment_form.s_all_investments_date }}
                    {{ search_investment_form.s_all_investments_date.label }}
                </label>
            </fieldset>
        </div>   

        <div class="borda">
            <fieldset>
                <legend>{% trans "Value" %} <span class="total">({{count_investments}})</span></legend>
    
                <label for="id_s_investment_from">{{ search_investment_form.s_investment_from.label }}</label>
                {{ search_investment_form.s_investment_from }}

                <label class="emlinha" for="id_s_investment_to">{{ search_investment_form.s_investment_to.label }}</label>
                {{ search_investment_form.s_investment_to }}

                <label for="id_s_all_investments_value" class="check"> 
                    {{ search_investment_form.s_all_investments_value }}
                    {{ search_investment_form.s_all_investments_value.label }}
                </label>
            </fieldset>
        </div>   

        <div class="borda">
            <fieldset>
                <legend>{% trans "Organization type" %} <span class="total">({{count_organization_types}})</span></legend>
                
                {{ search_investment_form.s_organization_type }}

                <label for="id_s_all_type_organizations" class="check"> 
                    {{ search_investment_form.s_all_type_organizations }}
                    {{ search_investment_form.s_all_type_organizations.label }}
                </label>

            </fieldset>
        </div>

        <div class="borda">
            <fieldset>
                <legend>{% trans "Organization" %} <span class="total">({{count_organizations}})</span></legend>
                
                {{ search_investment_form.s_organization }}

                <label for="id_s_all_organizations" class="check"> 
                    {{ search_investment_form.s_all_organizations }}
                    {{ search_investment_form.s_all_organizations.label }}
                </label>

            </fieldset>
        </div>

        <div class="borda">
            <fieldset>
                <legend>{% trans "Project Name" %} <span class="total">({{count_projects}})</span></legend>
                
                {{ search_investment_form.s_project_name }}

                <label for="id_s_all_project_name" class="check"> 
                    {{ search_investment_form.s_all_project_name }}
                    {{ search_investment_form.s_all_project_name.label }}
                </label>

            </fieldset>
        </div>

        <div class="borda ultimo">
            <fieldset>
                <legend>{% trans "Supported Region" %} <span class="total">({{count_recipient_entity_investments}})</span></legend>
                
                <label for="id_s_country">{{ search_investment_form.s_country.label }}</label>
                {{ search_investment_form.s_country }}

                <label for="id_s_state">{{ search_investment_form.s_state.label }}</label>
                {{ search_investment_form.s_state }}

            </fieldset>
        </div>

    </form>

    {% block extra_script %}
    <script type="text/javascript">
        jQuery(document).ready(function(){
            //Cria o estilo dos elementos combo.
            createCombo();

            //Chama o plugin de datepicker do jqueryUI.
            jQuery('.data').datepicker({dateFormat:'{{date_format}}'});

            //Formatação do campo de valor. Classe específica = numero
            jQuery('.numero').setMask('{{number_format}}');
        });
    </script>
    {% endblock %}   

</section>
<!-- Fim de Filtros de Busca por investimentos -->

ecofunds/templates/investment/form.html
{% load sekizai_tags tags i18n static cms_tags %}

{%block head%}
    {% addtoblock "css" %}
        <link type="text/css" rel="stylesheet" href="{% get_static_prefix %}css/ui-custom-theme/jquery-ui-1.9.2.custom.min.css" />
    {% endaddtoblock %}

    {% addtoblock "js" %}
        <!-- Funções gerais de cadastro -->
        <script type="text/javascript" src="{% get_static_prefix %}scripts/global/form.js"></script>
                
        <!-- Funções específicas dessa página -->
        <script type="text/javascript" src="{% get_static_prefix %}scripts/investment/form.js"></script>
    {% endaddtoblock %}
{% endblock %}

{% block base_content %}
    <section class="cadastro investimento">
        <header class="info-cadastro-preliminar">
            <h4 class="investidor">{% if formset.instance.pk %}{{formset.instance.funding_organization}}{% else %}{%trans "[Investor organization name]" %}{% endif %}</h4>
            <span class="ico seta-fluxo"></span>
            <h3 class="titulo-cadastro receptor">{% if formset.instance.pk %}{{formset.instance.recipient_organization}}{% else %}{%trans "[Recepient organization name]" %}{% endif %}</h3>
            
            <p class="autoria-data">
            {% if formset.instance.pk %}
                {% if formset.instance.updater %}
                {%trans "Last edited by " %}<a href="{% page_url 'user-form' %}" id="" class="editado-por">{{formset.instance.updater }}</a> {% trans "in" %} <span class="editado-em">{{formset.instance.updated_at}}</span>
                {% elif formset.instance.creater  %}
                {%trans "Last edited by " %}<a href="{% page_url 'user-form' %}" id="" class="editado-por">{{formset.instance.creater}}</a> {% trans "in" %} <span class="editado-em">{{formset.instance.created_at}}</span>
                {% endif %}
            {% endif %}
            </p>
        </header>

        <form method="post" action="" enctype="multipart/form-data" class="form-cadastro investimento">
            {% csrf_token %}
            
            <div class="controles superiores">
                <input type="submit" class="botao primario" value="{%trans "Save investment record" %}" />
                <a href="{% page_url 'home' %}" class="botao secundario">{%trans "Cancel" %}</a>
            </div>          
            
            <div class="mensagem-informativa">* {% trans "Required fields" %}</div>
            
            <div class="nonfielderrors">
                {{formset.non_field_errors}}
            </div>
            
            <div class="campos-formulario">
                <!-- Basic Information -->
                <fieldset class="info-cadastro basico">
                    <legend class="titulo-info">{% trans "Basic information"%}</legend>
                    {% if formset.instance.pk %}
                        <div class="grupo grupo-code">
                            <div class="envolve-campo">
                                <div class="titulo-campo">
                                    <label for="id_code">{% trans "Investment ID" %}</label>
                                </div>
                                
                                <div class="campos-editaveis">
                                    {{ formset.instance.code }}
                                </div>
                            </div>
                        </div>
                    {% endif %}                                            
                    
                    <div class="grupo grupo-investidor">
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_funding_organization"><span class="obrigatorio">{{ formset.funding_organization.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                <span class="links-adicionais">{% trans "or" %} <a href="{% page_url 'organization-form' %}">{% trans "Create new organization" %}</a></span>
                                {{ formset.funding_organization }}
                                {{ formset.funding_organization.errors }}
                            </div>
                        </div>
                        
                        <div class="envolve-campo ">
                            <div class="titulo-campo">
                                <label for="id_investor_project"><span class="obrigatorio">{{ formset.investor_project.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.investor_project }}
                                {{ formset.investor_project.errors }}
                            </div>
                        </div>
                        
                        <div id="investor-project-name" class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_funding_entity">{{ formset.funding_entity.label }}</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                <span class="links-adicionais">{% trans "or" %} <a href="{% page_url 'project-form' %}">{% trans "Create new project" %}</a></span>
                                {{ formset.funding_entity }}
                                {{ formset.funding_entity.errors }}
                            </div>
                        </div>
                    </div>                    
                                                  
                    <div class="grupo grupo-receptor">
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_recipient_organization"><span class="obrigatorio">{{ formset.recipient_organization.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                <span class="links-adicionais">{% trans "or" %} <a href="{% page_url 'organization-form' %}">{% trans "Create new organization" %}</a></span>
                                {{ formset.recipient_organization }}
                                {{ formset.recipient_organization.errors }}
                            </div>
                        </div>
                        
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_r_project"><span class="obrigatorio">{{ formset.r_project.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.r_project }}
                                {{ formset.r_project.errors }}
                            </div>
                        </div>
                        
                        <div id="recepient-project-name" class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_recipient_entity">{{ formset.recipient_entity.label }}</label>
                            </div>
                            <div class="campos-editaveis">
                                <span class="links-adicionais">{% trans "or" %} <a href="{% page_url 'project-form' %}">{% trans "Create new project" %}</a></span>
                                {{ formset.recipient_entity }}
                                {{ formset.recipient_entity.errors }}
                            </div>
                        </div>
                    </div>

                    <div class="grupo grupo-tipo">
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_type"><span class="obrigatorio">{{ formset.type.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.type }}
                                {{ formset.type.errors }}
                            </div>
                        </div>
                        
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_date"><span class="obrigatorio">{{ formset.date.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.date }}
                                {{ formset.date.errors }}
                            </div>
                        </div>
                        
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_estimated_completion"><span class="obrigatorio">{{ formset.estimated_completion.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.estimated_completion }}
                                {{ formset.estimated_completion.errors }}
                            </div>
                        </div>                                                                        
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_estimated_completion">{{ formset.third_party.label }}</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.third_party }}
                                {{ formset.third_party.errors }}
                            </div>
                        </div>                                                                        
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_investment_flow">{{ formset.investment_flow.label }}</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                {{ formset.investment_flow}}
                                {{ formset.investment_flow.errors }}
                            </div>
                        </div>                                                                        
                    </div>

                </fieldset>
                <!-- Fim Basic-->
                
                <!-- Amount information-->
                <fieldset class="info-cadastro valor">
                    <legend class="titulo-info">{% trans "Amount"%}</legend>
                
                    <div class="grupo grupo-valor">
                        <div class="envolve-campo">
                            <div class="titulo-campo">
                                <label for="id_currency"><span class="obrigatorio">{{ formset.currency.label }}*</span></label>
                            </div>
                            
                            <div class="campos-editaveis">
                                <span class="links-adicionais">{% trans "Amount in the date of the contract." %}</a></span>
                                {{ formset.currency }}
                                {{ formset.amount }}
                                
                                {{ formset.currency.errors }}
                                {{ formset.amount.errors }}
                            </div>            
                        </div>
                    </div>
                </fieldset> 
                <!-- Fim Amount information-->
                                                                               
                <!-- Attachments-->
                <fieldset class="info-cadastro anexos">
                    <legend class="titulo-info">{% trans "Attachments"%}</legend>
                    <p>
                        Teste
                    </p>       
                </fieldset>             
                <!--Fim  Attachments --> 
            </div>
            
            <div class="controles inferiores">
                <input type="submit" class="botao primario" value="{%trans "Save investment record" %}" />
                <a href="{% page_url 'home' %}" class="botao secundario">{%trans "Cancel" %}</a>
            </div>            
        </form>
        
        {% block extra_script %}
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('.ui-autocomplete-input').each(function(i,v){
                    jQuery(this).addClass('combo');
                });

                //Cria o estilo dos elementos combo.
                createCombo();

                //Chama o plugin de datepicker do jqueryUI.
                jQuery('.data').datepicker({dateFormat:'{{date_format}}'});

                //Formatação do campo de valor. Classe específica = numero
                jQuery('.numero').setMask('{{number_format}}');
            });
        </script>
        {% endblock %}
                        
    </section>
{%endblock%}

ecofunds/templates/investment/no-results.html
{% load cms_tags sekizai_tags tags i18n static %}

<!-- Nada encontrado -->
<div class="nada-econtrado">
    <h3>{% trans "No results match your seach." %}</h3>
    <p>{% trans "Try one of the investments below or make a new search." %}</p>
</div>
<!-- fim de Nada encontrado -->


<!-- Novos investimentos -->
<div class="relacao resumida novos-investimentos alinhado esquerda">
    <h3>{% trans "New investments" %}</h3>
    <ul>
        {% for investment in latest_investments %}
        <li>
            <h4><a href="{%page_url "investment-detail"%}?id={{investment.id}}" title="{{ investment.funding_organization.name }}">{{ investment.funding_organization.name }}</a></h4>
            <p>
                {{ investment.recipient_entity.title }}
            </p>
        </li>
        {% endfor %}                                                                              
    </ul>   
</div>
<!-- fim de novos investimentos -->


<!-- Novos projetos -->
<div class="relacao resumida novos-projetos alinhado direita">
    <h3>{% trans "Latest projects to receive investments" %}</h3>
    <ul>
        {% for project in new_project_investments %}
        <li>
            <h4><a href="{% page_url "project-detail" %}?id={{project.entity_id}}" title="{{ project.title }}">{{ project.title }}</a></h4>
            <p>
                {% autoescape off %}{{ project.resume }}{% endautoescape %}
            </p>
        </li>
        {% endfor %}                                                                           
    </ul>   
</div>
<!-- fim de novos projetos -->


                    