ecofunds/opportunity/urls.py
from django.conf.urls.defaults import *
from ecofunds.opportunity.models import FundingOpportunity

opportunities_dict = {
    'queryset': FundingOpportunity.published.all(),
    'date_field': 'pub_date',
}

opportunities_month_dict = {
    'queryset': FundingOpportunity.published.all(),
    'date_field': 'pub_date',
    'month_format': '%m',
}

urlpatterns = patterns('django.views.generic.date_based',
    (r'^$', 'archive_index', opportunities_dict, 'opportunity_index'),
    (r'^(?P<year>\d{4})/$', 'archive_year', opportunities_dict, 'opportunity_year'),
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/$', 'archive_month', opportunities_month_dict, 'opportunity_month'),
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$', 'archive_day', opportunities_month_dict, 'opportunity_day'),
    (r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', 
        'object_detail', opportunities_month_dict, 'opportunity_detail'),
)

ecofunds/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

from ecofunds.views import *

from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^opportunity/', include('ecofunds.opportunity.urls')),
    url(r'^ajax/lookups',include(ajax_select_urls)),
    url(r'^ajax/project/', include('ecofunds.project.urls')),
    url(r'^ajax/organization/', include('ecofunds.organization.urls')),
    url(r'^ajax/investment/', include('ecofunds.investment.urls')),
    #url(r'^ajax/suggest', GlobalSuggestListView.as_view()),
    url(r'^ajax/suggest', SearchSuggestListView.as_view()),
    url(r'^ajax/upload', uploadify_upload),
    url(r'^attachment/download/(?P<id>[\d]+)/$', FileDownload.as_view()),
    url(r'^maps/', include('ecofunds.maps.urls')),
    url(r'^user/',include('ecofunds.user.urls')),
    url(r'^new/$',AttachmentCreateView.as_view(),{},'upload-new'),
    url(r'^delete/(?P<pk>\d+)$',AttachmentDeleteView.as_view(),{},'upload-delete'),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        (r'^' + settings.MEDIA_URL.lstrip('/'), include('appmedia.urls')),
    ) + urlpatterns

ecofunds/opportunity/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin

class PublishedFundingOpportunityManager(models.Manager):
    """
        Filters out all unpublished and items with a publication date in the future
    """
    def get_query_set(self):
        return super(PublishedFundingOpportunityManager, self).get_query_set() \
                    .filter(is_published=True) \
                    .filter(pub_date__lte=datetime.datetime.now())

class FundingOpportunity(models.Model):
    """
    Funding opportunities
    """
    
    title           = models.CharField(_('Title'), max_length=255)
    slug            = models.SlugField(_('Slug'), unique_for_date='pub_date', 
                        help_text=_('A slug is a short name which uniquely identifies the news item for this day'))
    excerpt         = models.TextField(_('Excerpt'), blank=True)
    content         = models.TextField(_('Content'), blank=True)
    
    is_published    = models.BooleanField(_('Published'), default=False)
    pub_date        = models.DateTimeField(_('Publication date'), default=datetime.datetime.now())
    
    created         = models.DateTimeField(auto_now_add=True, editable=False)
    updated         = models.DateTimeField(auto_now=True, editable=False)
    
    published = PublishedFundingOpportunityManager()

    class Meta:
        db_table = u'ecofunds_fundingopportunities'
        verbose_name = _('Funding opportunity')
        verbose_name_plural = _('Funding opportunities')
        ordering = ('-pub_date', )
    
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return ('opportunity_detail', (), {
            'year': self.pub_date.strftime("%Y"),
            'month': self.pub_date.strftime("%m"),
            'day': self.pub_date.strftime("%d"),
            'slug': self.slug
        })


class FundingOpportunityPlugin(CMSPlugin):
    limit = models.PositiveIntegerField(
                _('Number of news items to show'), 
                help_text=_('Limits the number of items that will be displayed')
            )

ecofunds/opportunity/forms.py
from django import forms
from django.core.cache import cache
from django.utils.translation import ugettext_lazy as _

from ecofunds.models import OpportunityType, Activity
from ecofunds.forms import AdvancedSearchForm

OPPORTUNITYTYPE_CHOICES = (('', 'Choose an opportunity type'),) + tuple(opportunityType.objects.all().values_list('id', 'name'))
ACTIVITY_CHOICES = (('', 'Choose an activity type'),) + tuple(Activity.objects.all().values_list('activity_id', 'name'))

class OpportunityAdvancedSearchForm(AdvancedSearchForm):

    s_opportunity_type = forms.IntegerField(label=_('Opportunity type'), widget=forms.Select(choices=OPPORTUNITYTYPE_CHOICES, attrs={'class':''}))
    
    s_all_type_opportunities = forms.BooleanField(label=_('All opportunity types'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_opportunity_id = forms.IntegerField(widget=forms.HiddenInput())

    s_opportunity = forms.CharField(label=_('Opportunity'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of an opportunity')}))
    s_all_opportunities = forms.BooleanField(label=_('All opportunities'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_country = forms.CharField(label=_('Country'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a country')}))
    s_state = forms.CharField(label=_('State'), widget=forms.TextInput(attrs={'class':'combo','autocomplete':'off','placeholder': _('Enter the name of a state')}))

    s_investments_focus = forms.IntegerField(label=_('Investments focus'), widget=forms.Select(choices=ACTIVITY_CHOICES, attrs={'class':''}))
    
    s_all_investments_focus = forms.BooleanField(label=_('All project activities focus'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_investment_date_from = forms.CharField(label=_('From'), widget=forms.TextInput(attrs={'class':'data'}))
    s_investment_date_to = forms.CharField(label=_('To'), widget=forms.TextInput(attrs={'class':'data'}))
    s_all_investment_date = forms.BooleanField(label=_('All investments'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))

    s_estimated_investments_value_from = forms.CharField(label=_('Show investments from:'), widget=forms.TextInput(attrs={'class':'numero'}))
    s_estimated_investments_value_to = forms.CharField(label=_('To'), widget=forms.TextInput(attrs={'class':'numero'}))
    s_all_investments_received = forms.BooleanField(label=_('All investments received'), widget=forms.CheckboxInput(attrs={'class':'check', 'value': 0}))
    
    def _force_data(self):
        if not hasattr(self, 'cleaned_data'):
            self.is_valid()
        if not hasattr(self, 'cleaned_data'):
            self.cleaned_data = {}

    def get_value(self, key, persist=False):
        
        value = None
        if self.data.has_key(key):
            
            self._force_data()
            if self.cleaned_data.has_key(key):
                value = self.cleaned_data[key]

            if value:
                cache.set(key, value)
            else :
                value = self.data.get(key)

                if not value:
                    value = cache.get(key)
                    self.cleaned_data[key] = value
                else:
                    cache.set(key, value)
        else:
            if persist:
                value = cache.get(key)
                self._force_data()
                self.cleaned_data[key] = value
            else:
                cache.delete(key)

        return value

ecofunds/opportunity/views.py
# Create your views here.

ecofunds/templates/opportunity/advanced-search.html
{% load tags i18n %}
   <!-- Filtros de Busca por Oportunidades -->
   <section class="filtros oportunidades aberto">
        <header class="cabecalho">
            <h4>{% trans "Find opportunities by" %}</h4>
            <p><span class="seta cima cinza"></span>{% trans "Combine filters to improve your search" %}</p>
            <a class="botao primario ocultar-exibir-filtro" href="#" title=""><span class="ico pequeno seta"></span></a>
        </header>

        <form class="form-filtros oportunidades" action="#" method="post">
            {{ search_opportunity_form.page }}
            {{ search_opportunity_form.limit }}
            {{ search_opportunity_form.list_type }}
            {{ search_opportunity_form.order_by }}

            <div class="borda primeiro">
                <fieldset>
                    <legend>{% trans "Opportunity" %} <span class="total">({{ count_opportunities }})</span></legend>
                    
                    {{ search_opportunity_form.s_opportunity }}

                    <label for="id_s_all_opportunities" class="check"> 
                        {{ search_opportunity_form.s_all_opportunities }}
                        {{ search_opportunity_form.s_all_opportunities.label }}
                    </label>

                </fieldset>
            </div>

            <div class="borda">
                <fieldset>
                    <legend>{% trans "Opportunity type" %} <span class="total">({{ count_opportunity_types }})</span></legend>
                    
                    {{ search_opportunity_form.s_opportunity_type }}

                    <label for="id_s_all_type_opportunities" class="check"> 
                        {{ search_opportunity_form.s_all_type_opportunities }}
                        {{ search_opportunity_form.s_all_type_opportunities.label }}
                    </label>

                </fieldset>
            </div>

            <div class="borda">
                <fieldset>
                    <legend>{% trans "Supported location" %} <span class="total">({{ count_opportunity_regions }})</span></legend>
                    
                    <label for="id_s_country">{{ search_opportunity_form.s_country.label }}</label>
                    {{ search_opportunity_form.s_country }}

                    <label for="id_s_state">{{ search_opportunity_form.s_state.label }}</label>
                    {{ search_opportunity_form.s_state }}

                </fieldset>
            </div>

            <div class="borda">
                <fieldset>
                    <legend>{% trans "Investments focus" %} <span class="total">({{ count_project_activity_types }})</span></legend>
                    
                    {{ search_opportunity_form.s_investments_focus }}

                    <label for="id_s_all_investments_focus" class="check"> 
                        {{ search_opportunity_form.s_all_investments_focus }}
                        {{ search_opportunity_form.s_all_investments_focus.label }}
                    </label>

                </fieldset>
            </div>

            <div class="borda">
                <fieldset>
                    <legend>{% trans "Last investment date" %} <span class="total">({{ count_opportunity_investments }})</span></legend>
                    
                    {{ search_opportunity_form.s_investment_date_from }}

                    <label class="emlinha" for="id_investment_date_to">{{ search_opportunity_form.s_investment_date_to.label }}</label>
                    {{ search_opportunity_form.s_investment_date_to }}

                    <label for="id_s_all_investment_date" class="check"> 
                        {{ search_opportunity_form.s_all_investment_date }}
                        {{ search_opportunity_form.s_all_investment_date.label }}
                    </label>

                </fieldset>
            </div>                       

            <div class="borda ultimo">
                <fieldset>
                    <legend>{% trans "Estimated investments value" %} <span class="total">({{ count_recipient_opportunity }})</span></legend>
                    
                    <label for="id_s_estimated_investments_value_from">{{ search_opportunity_form.s_estimated_investments_value_from.label }}</label>
                    {{ search_opportunity_form.s_estimated_investments_value_from }}

                    <label class="emlinha" for="id_s_estimated_investments_value_to">{{ search_opportunity_form.s_estimated_investments_value_to.label }}</label>
                    {{ search_opportunity_form.s_estimated_investments_value_to }}

                    <label for="id_s_all_investments_received" class="check"> 
                        {{ search_opportunity_form.s_all_investments_received }}
                        {{ search_opportunity_form.s_all_investments_received.label }}
                    </label>

                </fieldset>
            </div>    

        </form>
    </section>
    <!-- Fim de Filtros de Busca por oportunidades -->

ecofunds/templates/opportunity/detail-bk.html
{% extends "base-cms.html" %}
{% load cms_tags %}

{% block base_content %}
    <h1>{{ object.title }}</h1>
    <p><span class="date">{{ object.pub_date }}</span><br/>
        {{ object.content|safe }}
    </p>
{% endblock %}

ecofunds/templates/opportunity/detail.html
{% load sekizai_tags tags i18n static %}

{% addtoblock "meta" %}

<!-- Facebook Meta Tags -->
    <meta property="og:title" content="{{ organization.name }}" /> 
    <meta property="og:type" content="detail organization" /> 
    <meta property="og:url" content="" /> 
    <meta property="og:image" content="{% if organization.image %}{{ organization.image.url }}{% else %}{% get_static_prefix %}images/organizacao-sem-foto.jpg{% endif %}" /> 
    <meta property="og:site_name" content="http://ecofundsdatabase.org"/> 
    <meta property="og:description" content="{% autoescape off %}{{ organization.mission }}{% endautoescape %}" /> 
<!-- End of Facebook Meta Tags -->

{% endaddtoblock %}

{% addtoblock "js" %}
<!-- Funções específicas dessa página -->
<script type="text/javascript" src="{% get_static_prefix %}scripts/organization/detail.js"></script>

<!-- Utilizado pelo Facebook -->
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=277399048946696";
        fjs.parentNode.insertBefore(js, fjs);
    }
    (document, 'script', 'facebook-jssdk'));
</script>
<!-- fim Utilizado pelo Facebook -->

<!-- Utilizado pelo Twitter -->
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
<!-- fim Utilizado pelo Twitter -->

{% endaddtoblock %}

<!-- area-site -->
<div class="area-site">
    <div class="container">
        <h2 class="ico ico-texto oportunidade-maior-branco">{% trans "Opportunities" %}</h2>    
    </div>
</div>
<!-- fim area-site -->

<div class="container">
    <!-- Link auxiliar -->
    <div class="link-auxiliar">
    	<a class="voltar link-destaque" href="#" title="{% trans "Previous search" %}">{% trans "Previous search" %}</a>
    </div>
    <!-- fim de Link auxiliar -->

    <!-- conteudo principal -->
    <div class="conteudo">
    	<div class="ficha organizacao">
            <input type="hidden" name="id" value="#" />
    		<h2 class="titulo-ficha">{% trans "Opportunity Name" %}</h2>
    		<div class="opcoes">
	    		<!-- menu com abas da ficha -->
	    		<div class="menu-abas">
			        <ul class="menu-abas-container">
		        		<li class="item aba"><a href="#informacoes">{% trans "Opportunity Record" %}</a></li>
			        </ul>
			    </div>
			    <!-- fim de menu com abas da ficha -->
			        
			    <!-- opcoes-adicionais da ficha -->
			    <div class="opcoes-adicionais">
                    
			        <ul class="opcoes-adicionais-container">
		        		<li class="item ico ico-texto impressao"><a href="#" id="bt-print">{% trans "Print" %}</a></li>     
			        </ul>
		    	</div>
		  		<!-- fim de opcoes-adicionais da ficha -->
	  		</div>

	        <!-- Informacoes da ficha -->
	        <section id="informacoes">

				<!-- Informações Básicas -->
				<div class="info basica">
					<h2 class="titulo-tabela">{% trans "Basic information" %}</h2>
					
					<!-- Compartilhar nas redes sociais -->
					<div class="compartilhar">
						<ul>
							<li class="facebook">
								<div class="fb-like" data-send="false" data-layout="button_count" data-width="90" data-show-faces="false" data-font="arial"></div>
							</li>
							<li class="twitter">
								<a href="https://twitter.com/share" class="twitter-share-button" data-via="funbio" data-lang="en">Tweet</a>
							</li>
							<li class="email"><a class="botao secundario" title="Enviar por email"><span class="ico pequeno email"></span>Email</a></li>
						</ul>
					</div>
					<!-- fim de compartilhar nas redes sociais -->

					<!-- tabela de informacoes basicas -->
					<table class="tabela horizontal" caption="Basic information" summary="">
						<tbody>
							<tr>
								<th class="titulo-registro" scope="row">{% trans "Scope" %}</th>
								<td class="conteudo-registro">Lorem ipsum...</td>
							</tr>
							<tr>
								<th class="titulo-registro" scope="row">{% trans "Objetivo" %}</th>
								<td class="conteudo-registro">Lorem...</td>
							</tr>
							<tr>
								<th class="titulo-registro" scope="row">{% trans "Description" %}</th>
								<td class="conteudo-registro">Lorem...</td>
							</tr>																						
						</tbody>
					</table>
					<!-- fim de tabela de informacoes basicas -->
				</div>
				<!-- fim de Informações Básicas -->

				<!-- Informações de investimentos -->
				<div class="info investimentos">
					<h2 class="titulo-tabela">{% trans "Amount" %}</h2>

					<!-- tabela de informacoes de investimentos -->
					<table class="tabela horizontal" caption="Address" summary="">					
						<tbody>
							<tr>
								<th class="titulo-registro" scope="row">{% trans "Funding value" %}</th>
								<td class="conteudo-registro destaque">$ 400,980 U.S. Dollars</td>
							</tr>
							<tr>
								<th class="titulo-registro" scope="row">{% trans "Original currency" %}</th>
								<td class="conteudo-registro destaque">$ 400,980 U.S. Dollars</td>
							</tr>																								
						</tbody>
					</table>
					<!-- fim de tabela de informacoes de investimentos -->
				</div>
				<!-- Fim de Informações de investimentos -->

				<!-- Informações de escopo geografico -->
				<div class="info escopo-geo">
					<h2 class="titulo-tabela">{% trans "Geographical scope" %}</h2>
					
					<!-- tabela de informacoes de escopo geografico -->
					<table class="tabela horizontal" caption="Geographical scope" summary="">
						<tbody>
							<tr>
								<td class="conteudo-registro">
									<ul class="lista-etiquetas">
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
									</ul>								
								</td>
							</tr>									
						</tbody>
					</table>				
					<!-- fim de tabela de informacoes de escopo geografico -->
				</div>
				<!-- fim de Informações de escopo geografico -->

				<!-- Informações de Atividades -->
				<div class="info atividades">
					<h2 class="titulo-tabela">{% trans "Supported activities" %}</h2>
					
					<!-- tabela de informacoes de Atividades -->
					<table class="tabela horizontal" caption="Geographical scope" summary="">
						<tbody>
							<tr>
								<td class="conteudo-registro">
									<ul class="lista-etiquetas">
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
										<li><a class="etiqueta" href="#" title="Search: Lorem">Lorem</a></li>
									</ul>									
								</td>
							</tr>									
						</tbody>
					</table>				
					<!-- fim de tabela de informacoes de Atividades -->
				</div>
				<!-- fim de Informações de Atividades -->

                {% if attachments.count > 0 %}
				<!-- Anexos -->
				<div class="info anexos">
					<h2 class="titulo-tabela">{% trans "Attachments" %}</h2>
						
					<!-- tabela de anexos -->
					<table class="tabela vertical" caption="Attachments" summary="">
						<thead>
							<tr>
								<th class="titulo-registro" scope="col">{% trans "File name" %}</th>
								<th class="titulo-registro" scope="col">{% trans "Date of publishing" %}</th>
								<th class="titulo-registro" colspan="2" scope="col"></th>
							</tr>
						</thead>

						<tfoot>
							<tr>
								<td class="rodape-tabela" colspan="4">
									<div class="paginacao-resultados">
									    {% pagination attachments True %}
									</div>
								</td>
							</tr>
						</tfoot>

						<tbody>
                            {% for attachment in attachments %}
							<tr>
								<td class="conteudo-registro texto"><a href="{{ attachment.path.url }}" title="{{ attachment.name }}">{{ attachment.name }}</a></td>
								<td class="conteudo-registro">{{ attachment.created_at|date:"d/M/Y" }}</td>
								<td class="conteudo-registro preview"><a href="{{ attachment.path.url }}" title="">{% trans "View" %}</a></td>
								<td class="conteudo-registro download"><a class="ico ico-texto pdf" href="#" title="">{% trans "Download" %}</a></td>
							</tr>
                            {% endfor %}											

						</tbody>
					</table>				
					<!-- fim de tabela de anexos -->
				</div>	
				<!-- fim de Anexos -->
                {% endif %}

	        </section>
	        <!-- fim de Informacoes da ficha -->

    	</div>

    </div>
    <!-- fim de conteudo -->

    <!-- barra lateral -->
    <div class="barra-lateral">
		<!-- Escopo Geográfico -->
		<section class="relacao resumida escopo-geo">
			<h3>{% trans "Similar geographical scope" %}</h3>
			<ul>
				<li>
					<h4><a href="#" title="Opportunity name">Opportunity name</a></h4>
					<p>
						Opportunity mission
					</p>
				</li>
                {% endfor %}																			
			</ul>	
		</section>
		<!-- fim de Escopo Geográfico -->
        {% endif %}

        {% if similar_activity_organizations.count > 0 %}
		<!-- Tipo de atividades -->
		<section class="relacao resumida tipo-atividades">
			<h3>{% trans "Similar activities types" %}</h3>
			<ul>
				{% for organization in similar_activity_organizations %}
				<li>
					<h4><a href="#" title="Opportunity name">Opportunity name</a></h4>
					<p>
						Opportunity mission
					</p>
				</li>
                {% endfor %}																			
			</ul>	
		</section>
		<!-- fim de Tipo de atividades --> 
		{% endif %}

		{% include "./map-link.html" %}
    </div>
    <!-- fim de barra lateral -->
</div>

ecofunds/templates/opportunity/fundingopportunity_archive.html
{% extends "base-cms.html" %}
{% load cms_tags %}

{% block base_content %}
    {% for opportunity in items %}
    <h2>{{ opportunity.title }}</h2>
    {% endfor %}
{% endblock %}

ecofunds/templates/opportunity/fundingopportunity_detail.html
{% extends "base-cms.html" %}
{% load cms_tags %}

{% block base_content %}
    {% for opportunity in items %}
    <h2>{{ opportunity.title }}</h2>
    {% endfor %}
{% endblock %}

ecofunds/templates/opportunity/latest.html
{% load tags i18n %}

<!-- oportunidades -->
<section class="relacao completa ultimas-oportunidades">
	<h3>{% trans "Funding opportunities" %}</h3>
	<ul>
		{% for opportunity in latest %}
			<li>
				<h4>{{ opportunity.title }}</h4>
				<p>{{ opportunity.excerpt }}</p>				
				<a class="veja-mais" href="{{ opportunity.get_absolute_url }}" title="{% trans "Show complete record" %}">{% trans "Show complete record" %}</a>
			</li>
		{% empty %}
		    <li>{% trans "No news yet" %}</li>
		{% endfor %}
	</ul>

	<a class="botao primario" href="{% page_url "opportunities" %}">{% trans "Find more opportunities" %}</a>		
</section>
<!-- fim de oportunidades -->